OcularEngineering/ocular

packages/ocular/core-config.js
packages/ocular/src/approaches/ask-retrieve-read.ts
packages/ocular/src/loaders/index.ts
packages/ocular/src/loaders/search.ts
packages/ocular/src/services/indexer.ts
packages/ocular/src/services/search.ts
packages/ocular/src/subscribers/search-indexing.ts

- Basic Vector Search Is Now Working
- Next Step: Optimize Search  to Include Other Approaches

Vector Search Is Now Working + Optimize Google Drive Indexing!

---

packages/apps/google-drive/src/services/google-drive.ts
packages/ocular-ui/components/search/search-results.tsx
packages/ocular/src/api/routes/member/search/ask.ts
packages/plugins/qdrant-vector-search-service/src/services/qdrant.ts
packages/types/src/interfaces/indexer-interface.ts
packages/utils/src/common/container.ts

- CL adds CoPilot Section Above Search Results On the UI.

Add CoPilot MVP UI  to Ocular UI

---

.gitignore
package-lock.json
package.json
packages/apps/asana/src/services/asana.ts
packages/apps/github/src/services/github.ts
packages/apps/gmail/src/services/gmail.ts
packages/plugins/azure-open-ai/package.json
packages/plugins/document-processor/tsconfig.json
packages/plugins/resend/package
packages/plugins/typesense-text-search-service/src/services/typesense.ts

- UnBlock contributors and ensure that Ocular can build on any local machine.

Clean Up Ocular

---

packages/apps/README.md
packages/apps/confluence/.babelrc
packages/apps/confluence/.gitignore
packages/apps/confluence/.npmignore
packages/apps/confluence/README.md
packages/apps/confluence/package.json
packages/apps/confluence/src/services/confluence.ts
packages/apps/confluence/src/services/oauth.ts
packages/apps/confluence/src/strategies/confluence.ts
packages/apps/confluence/tsconfig.json
packages/ocular/core-config.js

> Added Confluence app 
> Still facing db_entities error

Added Atlassian : Confluence App (Written by Vivek Lahole)

---

packages/ocular/package.json
packages/ocular/src/data-source.ts
packages/ocular/src/loaders/approaches.ts
packages/ocular/src/loaders/apps.ts
packages/ocular/src/loaders/models.ts
packages/ocular/src/loaders/module.ts
packages/ocular/src/loaders/plugins.ts
packages/ocular/src/loaders/repositories.ts
packages/ocular/src/loaders/services.ts

Used `fast-glob` to convert path according to OS

fix: glob issues on Windows

---

packages/ocular-ui/components/chat-layout.tsx
packages/ocular-ui/components/chat/chat-sidebar/chat-sidebar-content.tsx
packages/ocular-ui/components/chat/chat-sidebar/chat-sidebar.tsx
packages/ocular-ui/styles/globals.css

Adding new changes to the Chat Interface

Improvements to Chat

---

packages/apps/slack/src/services/slack.ts

minor fix as to recieve correct params for conversation for slack connector

fix: datatype error while fetching conversation id in slack connector

---

packages/apps/README.md
packages/ocular/src/loaders/apps.ts

1. Added Documentation for AppName Database Migration

AppName Database migration Documentation

---

packages/ocular-ui/components/search/search-results.tsx
packages/ocular-ui/pages/dashboard/search/results/index.tsx

Result Page Retouch

---

packages/ocular-ui/components/dashboard-layout.tsx
packages/ocular-ui/components/search/app-filter-option.tsx
packages/ocular-ui/components/search/app-filter-options.tsx
packages/ocular-ui/components/search/header-filter-toolbar.tsx
packages/ocular-ui/components/search/header.tsx
packages/ocular-ui/components/search/search-results.tsx
packages/ocular-ui/components/ui/skeletons.tsx
packages/ocular-ui/context/context.tsx
packages/ocular-ui/lib/global-state.tsx
packages/ocular-ui/pages/dashboard/search/index.tsx
packages/ocular-ui/pages/dashboard/search/results/index.tsx
packages/ocular-ui/services/api.js
packages/ocular/src/subscribers/search-indexing.ts

Adding Result filtering by App, Header, and Search Result Layout touches

Result filtering, Header, and Search Result Layout touches

---

packages/ocular-ui/components/date-picker.tsx
packages/ocular-ui/components/search/search-results.tsx
packages/ocular-ui/components/ui/skeletons.tsx
packages/ocular-ui/context/context.tsx
packages/ocular-ui/lib/global-state.tsx
packages/ocular-ui/pages/dashboard/search/results/index.tsx
packages/ocular-ui/services/api.js

The proposed PR introduces three key features: an Optimization Result Page, Date Filtering, and Null Case Handling. The Optimization Result Page provides a user-friendly interface to display the outcomes of performance improvements, allowing for easy interpretation and analysis of data. Date Filtering enables users to refine results based on specific time frames, enhancing the tool's usability for time-sensitive evaluations. Lastly, Null Case Handling ensures robustness by addressing scenarios where data might be incomplete or missing, preventing potential errors and improving the overall reliability of the application.

Optimization Result Page, Date Filtering, and Null Case Handling

---

packages/ocular/src/api/routes/member/search/search.ts
packages/plugins/document-processor/src/__tests__/document-processor.ts
packages/plugins/document-processor/src/lib/txt.ts
packages/plugins/qdrant-vector-search-service/src/__tests__/qdrant.ts
packages/plugins/qdrant-vector-search-service/src/services/qdrant.ts
packages/types/src/common/document.ts
packages/types/src/common/search.ts

{
"q":"Search Query",
"context": {
"top": 10,
"types": ["pdf"],
"sources": ["google-drive"]
}
}
---
- https://app.asana.com/0/0/1207144095050692

Filter Documents By Type

---

packages/plugins/embedder/.gitignore
packages/plugins/embedder/.npmignore
packages/plugins/embedder/jest.config.ts
packages/plugins/embedder/package.json
packages/plugins/embedder/src/__tests__/embedder
packages/plugins/embedder/src/services/embedder.ts
packages/plugins/embedder/tsconfig.json
packages/plugins/embedder/tsconfig.spec.json

---
- https://app.asana.com/0/0/1207216946001621

Add Embedding Plugin To Ocular

---

packages/ocular-ui/components/date-picker.tsx
packages/ocular-ui/pages/dashboard/marketplace/[slug].tsx
packages/ocular-ui/services/api.js

When date was not provided, we didn't have results. 
Made sure that we date if undefined, we don't pass it to the backend, so we basically get results regardless of the date.
---
- https://app.asana.com/0/0/1207375536077266

Fix Date Bug

---

packages/ocular/src/services/job-scheduler.ts

chore: update job-scheduler.ts

---

packages/apps/notion/src/strategies/notion.ts
packages/apps/webconnector/src/services/webConnector.ts
packages/apps/webconnector/src/strategies/webConnector.ts
packages/ocular-ui/components/marketplace/webConnector.tsx
packages/ocular-ui/pages/dashboard/marketplace/[slug].tsx
packages/ocular/core-config.js
packages/ocular/src/api/routes/admin/apps/updateApp.ts
packages/ocular/src/services/organisation.ts
packages/ocular/src/subscribers/search-indexing.ts

1. New UI for WebConnector including title , description and base URL link
2. Resolved Link persistent issue 
3. Redesigned API for install update App
4. Fixed Notion Strategy Error

New UI for Webconnector and code cleanup

---

packages/ocular-ui/lib/auth.ts
packages/ocular-ui/lib/global-state.tsx
packages/ocular-ui/lib/private-route.tsx
packages/ocular-ui/pages/_app.tsx

Streaming bug fixes and dashboard routes protection

Protect Dashboard Pages from Unauthenticated users

---

packages/ocular-ui/context/context.tsx
packages/ocular-ui/lib/auth-route.tsx
packages/ocular-ui/lib/global-state.tsx
packages/ocular-ui/lib/private-route.tsx
packages/ocular-ui/pages/_app.tsx
packages/ocular-ui/pages/sign-in.tsx

Hiding create account and sign in pages from logged in users
---
- https://app.asana.com/0/0/1207437051090277

hide create account and sign in pages from logged in users

---

packages/ocular-ui/components/files/file-uploader.tsx
packages/ocular-ui/components/files/files-dialog.tsx
packages/ocular-ui/components/files/uploaded-files-card.tsx
packages/ocular-ui/components/search/search-results.tsx
packages/ocular-ui/components/side-nav.tsx
packages/ocular-ui/components/ui/dialog.tsx
packages/ocular-ui/data/data.tsx
packages/ocular-ui/pages/dashboard/files/index.tsx
packages/ocular-ui/types/types.ts

Changing files page from page to dialog and also rendering list of files

Files Dialog

---

packages/ocular-ui/components/files/files-dialog.tsx
packages/ocular-ui/components/files/uploaded-files-card.tsx
packages/ocular-ui/context/context.tsx
packages/ocular-ui/lib/global-state.tsx
packages/ocular-ui/services/admin-api.ts

fetch files from backend

---

packages/ocular-ui/components/files/uploaded-files-card.tsx

File Dialog UI Updates

---

packages/ocular-ui/components/files/uploaded-files-card.tsx
packages/ocular-ui/components/marketplace/marketplace-layout.tsx
packages/ocular-ui/components/marketplace/web-connector/add-website-dialog.tsx
packages/ocular-ui/components/marketplace/web-connector/web-connector.tsx
packages/ocular-ui/components/search/search-results.tsx
packages/ocular-ui/components/ui/input.tsx
packages/ocular-ui/components/ui/textarea.tsx
packages/ocular-ui/lib/utils.ts
packages/ocular-ui/pages/dashboard/marketplace/[slug].tsx
packages/ocular-ui/pages/dashboard/marketplace/manage-apps.tsx

Adding Add website dialog
---
- https://app.asana.com/0/0/1207208742154887

Add Website Dialog

---

packages/apps/notion/src/services/notion.ts
packages/apps/notion/src/services/oauth.ts
packages/apps/notion/src/strategies/notion.ts
packages/ocular/core-config-dev.js

1. Notion Cleanup
2. API token strategy for Notion
3. Recursive Notion Page Calling
4. Error Logging

Notion : Pages Indexing , Cleanup , Recursive page crawling

---

packages/ocular-ui/components/marketplace/web-connector/add-website-dialog.tsx
packages/ocular-ui/components/marketplace/web-connector/web-connector.tsx
packages/ocular-ui/components/side-nav.tsx
packages/ocular-ui/context/context.tsx
packages/ocular-ui/lib/global-state.tsx
packages/ocular-ui/pages/dashboard/marketplace/[slug].tsx
packages/ocular-ui/pages/dashboard/marketplace/browse-apps.tsx

Cleaning up the Web Connector added links page

Web Connector Websites Page

---

packages/ocular-ui/components/marketplace/web-connector/web-connector.tsx

Add bottom margin

---

package-lock.json
packages/apps/gmail/src/strategies/gmail.ts
packages/apps/slack/package.json
packages/apps/slack/src/loaders/index.ts
packages/apps/slack/src/services/oauth.ts
packages/apps/slack/src/strategies/slack.ts
packages/ocular/core-config-dev.js
packages/ocular/src/services/app-authorization.ts

---
- https://app.asana.com/0/0/1207448218634156

Add Slack App To Ocular

---

packages/ocular-ui/components/marketplace/api-token-cards/asana-card.tsx
packages/ocular-ui/components/marketplace/api-token-cards/github-card.tsx
packages/ocular-ui/components/marketplace/api-token-cards/index.tsx
packages/ocular-ui/components/marketplace/api-token-cards/slack-card.tsx

1. Added Dynamic UI for Apps
2. Asana UI
3. Slack UI
4. Github UI
```sh
```
---

Apps API token cards for Apps

---

packages/ocular/src/migrations/1719014894470-add_metadata.ts
packages/ocular/src/models/document-metadata.ts
packages/ocular/src/services/document-metadata.ts

Return metadata In Search Results

---

packages/apps/asana/src/strategies/asana.ts
packages/apps/bitbucket/src/loaders/index.ts
packages/apps/github/src/loaders/index.ts
packages/apps/github/src/services/github.ts
packages/apps/github/src/services/oauth.ts
packages/apps/github/src/strategies/github.ts
packages/ocular-ui/components/marketplace/api-token-cards/github-card.tsx
packages/ocular/core-config-dev.js
packages/ocular/src/services/app-authorization.ts

Add GitHub Connector

---

packages/plugins/pinecone-vector-search-service/src/services/pinecone.ts

PineCone Plugin : Added addDocuments , deleteDocuments service

---

packages/ocular/core-config-local.js

Fix : core-config-local Kafka undefined error

---

packages/ocular-telemetry/package.json

Remove Old  Axios For Security Issues

---

package-lock.json
package.json

PineCone Deps

---

packages/ocular-models-server/requirements.txt
packages/ocular/src/services/app-authorization.ts

App Fixes : Notion , Jira , Web-Connector
